### ISSUE TITLE
Documentar Escopo e definir funcionalidades principais

### ISSUE THREAD

**Issue by Hilst** [Well-Being-App/well-being#1]
# Objetivo
Montar definição do escopo do projeto e definir funções fundamentais do sistema

# DOD
- Deve estar definido textualmente no arquivo README.md o motivo de ser do sistema e as funcionalidades
- Devem estar definidas as as funcionalidades MACROs no arquivo README.md

# Tasks
- [x] Realizar levantamento de requisitos em paralelo com o desenvolvimento de documento de Casos de Uso
- [x] Descrever escopo do sistema no README.md
- [x] Descrever funcionalidades principais no README.md
