### ISSUE TITLE
Estruturar Arquitetura Back

### ISSUE THREAD

**Issue by Hilst** [Well-Being-App/well-being#6]
# Objetivo
Definir tecnologias relacionadas ao Backend

# DOD
- Definição textual no arquivo arquitetura.md na partição de backend
- Motivação textual da tecnologia

# Tasks
- [X] Arquitetura inicial da aplicação
- [X] Database Schema para os dados
- [ ] Aprovação da Arquitetura
- [ ] Aprovação do Schema

**Comment by Arthurcrivilin** [comment]
Sugestão de uso: MongoDB - Pela praticidade em não precisar de um schema fixo

**Comment by Hilst** [comment]
- De banco concordo com o MongoDB, ou outros NoSQL, não sei muito dessa parte então deixo para vocês escolher eles
- De API talvez alguma(s) para coordenar as login e as chamadas. Facilita a parte do front. 
- Aí a arquitetura de uma ou várias APIs, microsserviço ou monólito seria definido pela granularidade do Front. Se às features forem muito diferentes aí valeria segregar o back e os bancos

**Comment by BiancaPuertaRocha** [comment]
a gente pode usar a tabela TACO (https://www.kaggle.com/datasets/ispangler/composio-nutricional-de-alimentos-taco?resource=download) para alimentar a base de dados.

**Comment by Hilst** [comment]
Para ajudar, parece que existe uma API já podemos incluir no nosso back um instância dela
https://taco-api.netlify.app/#sobre-o-projeto-taco

**Comment by BiancaPuertaRocha** [comment]
@Hilst eu vi ela, mas parece que ela nao ta online né? so que a gente pode subir ela tambem como ele mostra nessa doc, ai seriam 2 apis. Tem que subir pra ver os endpoints que tem nela mas deve ajudar sim!

**Comment by Arthurcrivilin** [comment]
Vou estar fazendo a classe Schema da nossa database com base nessa da TACO. Vamos ter o schema e teríamos esses dados importados em nossa database, descartando a necessidade de um container como API separado da nossa.
